{{- if .Values.extraConfigMaps }}
{{- range .Values.extraConfigMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
data: {{ .data | toYaml | nindent 2 }}
{{- end }}
{{- end }}
