{{- if and .Values.networkPolicy.enabled .Values.service.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}-wireguard"
  labels:
    app: "{{ .Release.Name }}-wireguard"
spec:
  podSelector:
    matchLabels:
      app: "{{ .Release.Name }}-wireguard"
  ingress:
    - ports:
        - protocol: UDP
          port: {{ .Values.service.port }}
        {{- if .Values.healthSideCar.enabled }}
        - protocol: TCP
          port: {{ .Values.healthSideCar.service.port }}
        {{- end }}
  policyTypes:
    - Ingress
{{- end }}
