---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
automountServiceAccountToken: false
{{- if .Values.healthSideCar.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-read-pods
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-pod-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
