{{- if .Values.metrics.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-exporter-wireguard"
  labels:
    app: "{{ .Release.Name }}-exporter-wireguard"
    app.kubernetes.io/component: metrics
    {{- if .Values.metrics.service.labels }}
    {{- toYaml .Values.metrics.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml .Values.metrics.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: exporter
    protocol: TCP
    port: {{ .Values.metrics.service.port }}
    targetPort: {{ .Values.metrics.service.port }}
  selector:
    app: "{{ .Release.Name }}-wireguard"
{{- end }}
