{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "eq-backend.fullname" . }}
  labels:
    {{- include "eq-backend.labels" . | nindent 4 }}
spec:{{ .Values.secretManager.spec | toYaml | nindent 2 }}
{{- end }}
