image:
  name: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
cmd: "/app/Migrations migrate"

job:
  backoffLimit: 1
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"

waitForDb:
  enabled: false
  image: busybox

db:
  maxAttempts: 30
  secretName: ""
  host: ""
  port: ""

podSecurityContext: {}

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
