image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
cmd: "/app/Migrations migrate"

job:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"

waitForDb:
  enabled: false
  image: busybox

db:
  secretName: ""
  host: ""
  port: ""
