image:
  name: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
cmd: "/app/Migrations migrate"

job:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
waitForDb:
  enabled: false
  image: busybox

db:
  maxAttempts: 30
  secretName: ""
  host: ""
  port: ""

podSecurityContext: {}

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
