{{- if .Values.ingress.enabled }}
{{- $fullName := include "main.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "main.labels" . | nindent 4}}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . |nindent 4}}
  {{- end }}
spec:
  ingressClassName: {{.Values.ingress.className | quote }}
  rules:
    - host: main.{{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "main.fullname" . }}
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - main.{{ .Values.ingress.host }}
      secretName: {{ .Release.Name }}-main-tls
{{- end }}