{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault:8200"
    vaultSkipTLSVerify: "true"
    roleName: {{ .Release.Namespace | quote }}
    objects: |
      {{- range .Values.secretManager.secrets }}
      - objectName: {{ .name }}
        secretPath: {{ .path }}
        secretKey: {{ .key }}
      {{- end }}
  secretObjects:
    {{- range .Values.secretManager.secrets }}
    - secretName: {{ .name }}
      type: {{ .type }}
      data:
        - objectName: {{ .name }}
          key: {{ .key }}
    {{- end }}
{{- end }}
