{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault:8200"
    vaultSkipTLSVerify: "true"
    roleName: {{ .Release.Namespace | quote }}
    objects: |
      {{- range .Values.secretManager.secrets }}
      {{- $secretName := .name }}
      {{- $secretPath := .path }}
      {{- range .keys }}
      - objectName: {{ $secretName }}-{{ . }}
        secretPath: {{ $secretPath }}
        secretKey: {{ . }}
      {{- end }}
      {{- end }}
  secretObjects:
    {{- range .Values.secretManager.secrets }}
    - secretName: {{ .name }}
      type: {{ .type }}
      data:
      {{- $secretName := .name }}
      {{- range .keys }}
        - objectName: {{ $secretName}}-{{ . }}
          key: {{ . }}
      {{- end }}
    {{- end }}
{{- end }}
