apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migrations.fullname" . }}
  labels:
    {{- include "migrations.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.job.annotations | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "migrations.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: migrator
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.cmd }}
          command:
            {{- if kindIs "string" .Values.cmd }}
            - "sh"
            - "-c"
            - "{{ .Values.cmd }}"
            {{- else }}
            {{- toYaml .Values.cmd | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretName }}
      {{- if .Values.waitForDb.enabled }}
      initContainers:
        - name: wait-for-db
          image: {{ .Values.waitForDb.image }}
          imagePullPolicy: {{ .Values.waitForDb.pullPolicy }}
          command:
            - 'sh'
            - '-c'
            - |
              attempts=0
              max_attempts={{ .Values.db.maxAttempts | default 30 }}
              until nc -z {{ .Values.db.host }} {{ .Values.db.port }}; do
                attempts=$((attempts+1))
                if [ $attempts -ge $max_attempts ]; then
                  echo "Failed to connect to DB after $max_attempts attempts. Aborting."
                  exit 1
                fi
                echo "Waiting for DB... (attempt $attempts/$max_attempts)"
                sleep 10
              done
              echo "DB connection established!"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- end }}
  # Automatically remove finished Jobs after a period
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
